### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by shdudwns** [Apollo-SoftwareTeam/Apollo-Linux-Installer#1]
Improperly selected! Restart the script, and then chose again.
root@flownetubuntu:~/test# l                                                                      Linux-Installer.sh*
root@flownetubuntu:~/test# ./Linux-Installer.sh -r
Connecting to the SpigotPE files
Loading
Loading.
Loading..
Loading...
 Installing the latest SpigotPE.phar please wait.
Trying to install the latest PHP-BINARY please wsit.
        1) Linux x86
Improperly selected! Restart the script, and then chose again.
root@flownetubuntu:~/test#

**Comment by Fabiansigala** [comment]
Try now it wasn't finished it should work now
